version: "2"
run:
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
  settings:
    gocritic:
      disabled-checks:
        - commentedOutCode
        - evalOrder
      enabled-tags:
        - diagnostic
        - performance
        - style
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G404
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - mocks
      - testdata
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - mocks
      - testdata
      - third_party$
      - builtin$
      - examples$
