// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package goidempo

import (
	"errors"
	"fmt"
)

const (
	// CacheProviderDatabase is a CacheProvider of type database.
	CacheProviderDatabase CacheProvider = "database"
	// CacheProviderRedis is a CacheProvider of type redis.
	CacheProviderRedis CacheProvider = "redis"
	// CacheProviderMemory is a CacheProvider of type memory.
	CacheProviderMemory CacheProvider = "memory"
)

var ErrInvalidCacheProvider = errors.New("not a valid CacheProvider")

// String implements the Stringer interface.
func (x CacheProvider) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CacheProvider) IsValid() bool {
	_, err := ParseCacheProvider(string(x))
	return err == nil
}

var _CacheProviderValue = map[string]CacheProvider{
	"database": CacheProviderDatabase,
	"redis":    CacheProviderRedis,
	"memory":   CacheProviderMemory,
}

// ParseCacheProvider attempts to convert a string to a CacheProvider.
func ParseCacheProvider(name string) (CacheProvider, error) {
	if x, ok := _CacheProviderValue[name]; ok {
		return x, nil
	}
	return CacheProvider(""), fmt.Errorf("%s is %w", name, ErrInvalidCacheProvider)
}
